FROM node:14.0.0-alpine


WORKDIR /src

RUN mkdir -p /src/node_modules  /src/dist
RUN chown -R node:node /src/node_modules /src/dist

COPY --chown=node:node package.json package-lock.json  /src/

RUN npm install

COPY --chown=node:node . /src

USER node

EXPOSE 8080
CMD npm run start
