version: "3.7"
services:
  stock-exchange-picker:
    build:
     context: .
     dockerfile: ./DockerFile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
